version: '2.1'

volumes:
   db-backups:
   geoserver-data:
   geo-db-data:

services:
  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
        - geo-db-data:/var/lib/postgresql
    ports:
      - "25434:5432"
    env_file:
    - geoserver/docker-env/db.env
    healthcheck:
      test: "exit 0"

  geoserver:
    image: kartoza/geoserver:2.15.2
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - ./geoserver/.data:/opt/data
    ports:
      - "8600:8080"
    env_file:
      - geoserver/docker-env/geoserver.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3


  db-dbbackups:
    image: kartoza/pg-backup:11.0
    volumes:
    - db-backups:/backups
    env_file:
    - geoserver/docker-env/db-backups.env
    depends_on:
      db:
        condition: service_healthy

  # adminer:
  #   image: adminer
  #   # restart: always
  #   ports:
  #     - 8700:8080

  ged:
    image: seeris/ged:0.1.0
    ports:
      - 8800:9500
    command: bash f main
    # environment:
    #   - STAGE=dev
